### PR TITLE
.gitlab-ci.yml: Switch to new runner on sonoma

### PR DESCRIPTION
**Pull request by t-b**
- [x] ReportGenerator step fails, see https://gitlab.byte-physics.de:4001/mirror/igortest/-/jobs/115314

### CODE REVIEW

**Comment by t-b** [comment]
@Garados007 Still the same error, see https://gitlab.byte-physics.de:4001/mirror/igortest/-/jobs/115650.

**Comment by Garados007** [comment]
I logged into the CI machine to have access to the docker image (it would take ages to download the image) and found the issue. I am working on a solution.

**Comment by t-b** [comment]
> I logged into the CI machine to have access to the docker image (it would take ages to download the image) and found the issue. I am working on a solution.

Nice. Sure, do log in. We have it exactly for this.

**Comment by t-b** [comment]
Restarted CI.

**Comment by t-b** [comment]
@Garados007 ✨

**Review by Garados007 — APPROVED** [review]
I only approve the changes made by Thomas. I can't approve my fix to the report generator call. 😉

**Comment by t-b** [comment]
Well looks like automation killed your idea. But I do think this is good to go anyway.

**Pull request merged**
